### ISSUE TITLE
Social Media lInks

### ISSUE THREAD

**Issue by JFelz** [bigtinytales/bigtinytales.github.io#1]
On footer on every page
- Instagram:
- https://www.instagram.com/bigtinytales/
- Facebook
- https://www.facebook.com/profile.php?id=100093063552051
- Youtube
- https://www.youtube.com/@BigTinyTales/
- Twitter(X)
- https://twitter.com/bigtinytales
- Tik Tok
- https://www.tiktok.com/@bigtinytales

**Comment by jjsub** [comment]
![Image](https://github.com/bigtinytales/bigtinytales.github.io/assets/7912104/954a51ee-43cf-4e3c-94cf-e61c38a99017)
